version: '3'
services:
  mongodb:
    image: mongo:8.0.4
    container_name: mongo-pwndoc
    volumes:
      - ./backend/mongo-data:/data/db
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - MONGO_DB:pwndoc
    networks:
      - backend

  pwndoc-backend:
    build: ./backend
    image: chapizze/pwndoc1a-backend:1.0
    container_name: pwndoc-backend
    secrets:
      - clientID
      - clientSecret
      - attachmentKey
      - attachmentIV
      - key
      - salt
    volumes:
      - ./backend/report-templates:/app/report-templates
      - ./backend/src/config:/app/src/config
    depends_on:
      - mongodb
    restart: always
    ports:
      - 4242:4242
    links:
      - mongodb
    networks: 
      - backend

  pwndoc-frontend:
    build: ./frontend
    image: chapizze/pwndoc1a-frontend:1.0
    container_name: pwndoc-frontend
    restart: always
    ports:
      - 8443:8443
    networks:
      - backend

  pwndoc-ai:
    build:
      context: .
      dockerfile: ./backend/Dockerfile-llama
    image: chapizze/llama:1.0
    container_name: llama-server
    restart: always
    ports:
      - 8888:8888
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:
      driver: bridge

secrets:
  clientID:
    file: resources/clientid.txt
  clientSecret:
    file: resources/clientsecret.txt
  attachmentKey:
    file: resources/attachmentKey
  attachmentIV:
    file: resources/attachmentIV
  key:
    file: resources/key
  salt:
    file: resources/salt