version: '3'
services:

  backend-test:
    image: pwndoc/pwndoc:backend-test
    build: 
      context: .
      dockerfile: Dockerfile.test
    container_name: pwndoc-backend-test
    secrets:
      - clientID
      - clientSecret
      - attachmentKey
      - attachmentIV
      - key
      - salt
    volumes:
      - ./report-templates:/app/report-templates
      - ./tests:/app/tests
      - ./src:/app/src
      - ./ssl:/app/ssl
      - ./jest.config.js:/app/jest.config.js
      - ./resources:/app/resources
    environment:
      API_URL: https://localhost:5252
    network_mode: host

secrets:
  clientID:
    file: resources/clientid.txt
  clientSecret:
    file: resources/clientsecret.txt
  attachmentKey:
    file: resources/attachmentKey
  attachmentIV:
    file: resources/attachmentIV
  key:
    file: resources/key
  salt:
    file: resources/salt