version: '3'
services:
  mongodb-test:
    image: mongo:4.2.15
    container_name: mongo-pwndoc-test
    volumes:
      - ./mongo-data-test:/data/db
    restart: always
    environment:
      - MONGO_DB:pwndoc
    network_mode: host

  backend-test:
    image: yeln4ts/pwndoc:backend-test
    build: 
      context: .
      dockerfile:  Dockerfile.test
    container_name: pwndoc-backend-test
    secrets:
      - clientID
      - clientSecret
      - attachmentKey
      - attachmentIV
      - key
      - salt
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
      - ./jest.config.js:/app/jest.config.js
      - ./resources/:/app/resources
    environment:
      API_URL: https://localhost:4242
    depends_on:
      - mongodb-test
    network_mode: host

volumes:
  mongo-data-test:

secrets:
  clientID:
    file: resources/clientid.txt
  clientSecret:
    file: resources/clientsecret.txt
  attachmentKey:
    file: resources/attachmentKey
  attachmentIV:
    file: resources/attachmentIV
  key:
    file: resources/key
  salt:
    file: resources/salt