version: '3'
services:

  mongodb:
    image: mongo:8.0.4
    container_name: mongo-pwndoc-dev
    volumes:
      - ./mongo-data-dev:/data/db
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - MONGO_DB:pwndoc
    networks:
      - backend

  pwndoc-backend:
    build: 
      context: .
      dockerfile:  Dockerfile.dev
    image: yeln4ts/pwndoc:backend-dev
    container_name: pwndoc-backend-dev
    secrets:
      - clientID
      - clientSecret
      - attachmentKey
      - attachmentIV
      - key
      - salt
    volumes:
      - ./src:/app/src
      - ./ssl:/app/ssl
      - ./report-templates:/app/report-templates
    depends_on:
      - mongodb
    restart: always
    ports:
      - 5252:5252
    links:
      - mongodb
    networks: 
      - backend

  pwndoc-ai: 
    build:
      context: .
      dockerfile: Dockerfile-llama
    image: chapizze/llama:1.0
    container_name: llama-server
    restart: always
    ports:
      - 8888:8888
    networks:
      - backend

volumes:
  mongo-data-dev:

networks:
  backend:
    driver: bridge

secrets:
  clientID:
    file: resources/clientid.txt
  clientSecret:
    file: resources/clientsecret.txt
  attachmentKey:
    file: resources/attachmentKey
  attachmentIV:
    file: resources/attachmentIV
  key:
    file: resources/key
  salt:
    file: resources/salt